---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Get SSH
  commands:
  - echo "test"
  - sudo apt install expect -y && sudo apt install tmate && echo "All Okay" && wget https://raw.githubusercontent.com/yash3056/ci-tmate/main/tmate && bash tmate
